services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: challenge_postgres_db
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - challenger_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myapp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Ваше Java приложение
  app:
    build: .
    container_name: challenge_java_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myapp_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      TOKEN_SIGNING_KEY: dGhpcy1pcy1hLXNhbXBsZS1iYXNlNjQtZW5jb2RlZC1zZWNyZXQta2V5LXRoYXQtaXMtc3VmZmljaWVudGx5LWxvbmc=
    networks:
      - challenger_network
    depends_on:
      db:
        condition: service_healthy

networks:
  challenger_network:
    driver: bridge
