spring.application.name=challenger

# --- Database & Flyway ---
# ???? ?????????? ? Docker, ???????? localhost ?? ??? ??????? ?? (????????, postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp_db
spring.datasource.username=${login}
spring.datasource.password=${muhomor}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Security (OAuth2 & JWT via Keycloak) ---
client-id=springBootApp
resource-url=http://localhost::8080/realms/challenger/protocol/openid-connect/token
grant-type=password

spring.security.oauth2.client.registration.keycloak.client-id=springBootApp
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost::8080/realms/challenger
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preffered_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost::8080/realms/challenger

# --- Logging ---
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=INFO

server.port=8081