ALTER TABLE challenges
    ADD COLUMN creator_id BIGINT,
    ADD COLUMN deadline TIMESTAMP,
    ADD COLUMN proof_type VARCHAR(255),
    ADD COLUMN status VARCHAR(255),
    ADD COLUMN winner_id BIGINT;

ALTER TABLE challenges
    ADD CONSTRAINT fk_creator
    FOREIGN KEY (creator_id)
    REFERENCES users(id);

ALTER TABLE challenges
    ADD CONSTRAINT fk_winner
    FOREIGN KEY (winner_id)
    REFERENCES users(id);

CREATE TABLE proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    media_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (challenge_id) REFERENCES challenges (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE user_challenge_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    challenge_id BIGINT NOT NULL,
    streak INT NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (challenge_id) REFERENCES challenges (id)
);
